Tracker:AddLocations("locations/(LVL 1).json")
Tracker:AddLocations("locations/(LVL 2).json")
Tracker:AddLocations("locations/(LVL 3).json")
Tracker:AddLocations("locations/(LVL 4).json")
Tracker:AddLocations("locations/(LVL 5).json")
Tracker:AddLocations("locations/(LVL 6).json")
Tracker:AddLocations("locations/(LVL 7).json")
Tracker:AddLocations("locations/Goal.json")
Tracker:AddLocations("locations/Overworld.json")
