//"Place location checks in correct spots"
//"Logic for specific settings"
//"Wasp logic for vehicles"
//"Forward logic?"
//"Mission logic for randomized vehicles"
//"Attach size logic to vehicles"
//"Check for specific cars on car-wasp logic"